<<<<<<< HEAD
# Generated by Django 4.2 on 2026-05-11 12:04

=======
>>>>>>> b13a5327cb6779918b9c3c834fb4f570beafc0d3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('scholarship_test', '0012_scholarshiptestfaculty_models'),
=======
        ("scholarship_test", "0012_scholarshiptestfaculty_models"),
>>>>>>> b13a5327cb6779918b9c3c834fb4f570beafc0d3
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='scholarshiptest',
            name='original_word_file',
            field=models.FileField(blank=True, null=True, upload_to='scholarship_test_files/'),
=======
            model_name="scholarshiptest",
            name="original_word_file",
            field=models.FileField(blank=True, null=True, upload_to="scholarship_test_files/"),
>>>>>>> b13a5327cb6779918b9c3c834fb4f570beafc0d3
        ),
    ]
