# Generated by Django 4.2 on 2026-06-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_test', '0016_merge_scholarshiptest_0015s'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scholarshipstudentleaderboard',
            index=models.Index(fields=['student_batch', 'updated_at'], name='ssl_batch_updated'),
        ),
        migrations.AddIndex(
            model_name='scholarshiptest',
            index=models.Index(fields=['status', 'scheduled_start_at', 'id'], name='st_status_sched_id'),
        ),
        migrations.AddIndex(
            model_name='scholarshiptest',
            index=models.Index(fields=['status', 'scheduled_start_at', 'created_at'], name='st_status_sched_created'),
        ),
        migrations.AddIndex(
            model_name='scholarshiptestattempt',
            index=models.Index(fields=['portal_student', 'status', 'test'], name='sta_portal_status_test'),
        ),
        migrations.AddIndex(
            model_name='scholarshiptestattempt',
            index=models.Index(fields=['test', 'status', 'test_completed_at', 'test_started_at', 'id'], name='sta_test_status_done'),
        ),
        migrations.AddIndex(
            model_name='scholarshiptestattempt',
            index=models.Index(fields=['status', 'test_completed_at'], name='sta_status_completed'),
        ),
        migrations.AddIndex(
            model_name='scholarshiptestfacultyattendance',
            index=models.Index(fields=['test', 'subject', 'portal_student'], name='stfa_test_sub_student'),
        ),
        migrations.AddIndex(
            model_name='scholarshiptestfacultynote',
            index=models.Index(fields=['test', '-created_at', '-id'], name='stfn_test_created'),
        ),
    ]
