services:

  db:
    image: mysql:8.0
    container_name: rankers-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Vishal@2026
      MYSQL_DATABASE: rankers_db

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pVishal@2026"]
      interval: 10s
      timeout: 5s
      retries: 15

  redis:
    image: redis:7-alpine
    container_name: rankers-redis
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10


  web:
    build: .
    container_name: rankers-app
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      REDIS_URL: redis://redis:6379/1
      DJANGO_STATIC_ROOT: /app/staticfiles
      DJANGO_MEDIA_ROOT: /app/media

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn sds_main.wsgi:application
      --bind 0.0.0.0:8000
      --workers $${GUNICORN_WORKERS:-4}
      --threads $${GUNICORN_THREADS:-4}
      --timeout $${GUNICORN_TIMEOUT:-90}
      --access-logfile -
      --error-logfile -
      "

    expose:
      - "8000"

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    healthcheck:
      test: ["CMD-SHELL", "python manage.py check || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.27-alpine
    container_name: rankers-nginx
    restart: unless-stopped

    depends_on:
      - web

    ports:
      - "8081:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro


volumes:
  mysql_data:
  static_volume:
  media_volume:
